# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 20:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('template_id', models.UUIDField()),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('personalisation', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsNotificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('template_id', models.UUIDField()),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('personalisation', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
