# Generated by Django 2.0 on 2017-12-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('template_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('email', 'template_id'),
            },
        ),
    ]
