# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationrequest',
            name='service_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
