# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_emailnotificationrequest_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotificationrequest',
            name='service_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
