# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-28 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_smsnotificationrequest_service_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
